apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    argocd/app-name: value
    github.com/project-slug: 'argoproj/argo-cd'
  name: my-kubernetes-component
spec:
  lifecycle: production
  owner: my-team
  type: service
